// Catálogo de canciones para el juego.
// Cada canción tiene título, artista y un emoji decorativo.
const SONGS = [
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", emoji: "🌴" },
  { title: "Bailando", artist: "Enrique Iglesias", emoji: "💃" },
  { title: "Macarena", artist: "Los del Río", emoji: "🕺" },
  { title: "Waka Waka", artist: "Shakira", emoji: "⚽" },
  { title: "La Bamba", artist: "Ritchie Valens", emoji: "🎸" },
  { title: "Bailar Pegados", artist: "Sergio Dalma", emoji: "💞" },
  { title: "La Tortura", artist: "Shakira ft. Alejandro Sanz", emoji: "🔥" },
  { title: "Gasolina", artist: "Daddy Yankee", emoji: "⛽" },
  { title: "Dance Monkey", artist: "Tones and I", emoji: "🐒" },
  { title: "Shape of You", artist: "Ed Sheeran", emoji: "💘" },
  { title: "Blinding Lights", artist: "The Weeknd", emoji: "🌃" },
  { title: "Bohemian Rhapsody", artist: "Queen", emoji: "👑" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", emoji: "🎸" },
  { title: "Thriller", artist: "Michael Jackson", emoji: "🧟" },
  { title: "Billie Jean", artist: "Michael Jackson", emoji: "✨" },
  { title: "Single Ladies", artist: "Beyoncé", emoji: "💍" },
  { title: "Bad Guy", artist: "Billie Eilish", emoji: "😈" },
  { title: "Levitating", artist: "Dua Lipa", emoji: "🪐" },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", emoji: "🎺" },
  { title: "Wonderwall", artist: "Oasis", emoji: "🎶" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", emoji: "🌟" },
  { title: "Dancing Queen", artist: "ABBA", emoji: "👸" },
  { title: "Y.M.C.A.", artist: "Village People", emoji: "🛟" },
  { title: "Thunderstruck", artist: "AC/DC", emoji: "⚡" },
  { title: "Hotel California", artist: "Eagles", emoji: "🏨" },
  { title: "Sweet Caroline", artist: "Neil Diamond", emoji: "🍬" },
  { title: "Mr. Brightside", artist: "The Killers", emoji: "🌞" },
  { title: "Bad Romance", artist: "Lady Gaga", emoji: "💔" },
  { title: "Toxic", artist: "Britney Spears", emoji: "☠️" },
  { title: "Hips Don't Lie", artist: "Shakira ft. Wyclef Jean", emoji: "🍑" },
  { title: "Sofía", artist: "Álvaro Soler", emoji: "☀️" },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", emoji: "🎉" },
  { title: "Vente Pa' Ca", artist: "Ricky Martin ft. Maluma", emoji: "🌶️" },
  { title: "Calma", artist: "Pedro Capó & Farruko", emoji: "🏖️" },
  { title: "Mi Gente", artist: "J Balvin & Willy William", emoji: "🌎" },
  { title: "Tusa", artist: "Karol G ft. Nicki Minaj", emoji: "👛" },
  { title: "Con Altura", artist: "Rosalía & J Balvin", emoji: "✈️" },
  { title: "Malamente", artist: "Rosalía", emoji: "🌹" },
  { title: "Pepas", artist: "Farruko", emoji: "💊" },
  { title: "Provenza", artist: "Karol G", emoji: "🌺" },
  { title: "Saoko", artist: "Rosalía", emoji: "🏍️" },
  { title: "La Vida es un Carnaval", artist: "Celia Cruz", emoji: "🎭" },
  { title: "El Ritmo No Perdona", artist: "Daddy Yankee", emoji: "🥁" },
  { title: "Suavemente", artist: "Elvis Crespo", emoji: "💋" },
  { title: "Bamboléo", artist: "Gipsy Kings", emoji: "🎻" },
  { title: "Asereje", artist: "Las Ketchup", emoji: "🍅" },
  { title: "Aserejé", artist: "Las Ketchup", emoji: "🥫" },
  { title: "We Will Rock You", artist: "Queen", emoji: "🪨" },
  { title: "I Will Survive", artist: "Gloria Gaynor", emoji: "💪" },
  { title: "September", artist: "Earth, Wind & Fire", emoji: "🍂" },
];
